[tools]
poetry = { version = "latest", pyproject = "{{ config_root }}/pyproject.toml" }
python = "3.14.3"

[tasks.run]
description = "run the project"
run = "poetry run python src/gs_dotfiles/__main__.py"

[tasks.test]
description = "run pytests"
run = "poetry run pytest"

[tasks.textual]
description = "Runs app with textual dev tools."
run = "poetry run textual run --dev src/gs_dotfiles/__main__.py"
